// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Music;

public final class controlePrxHelper extends Ice.ObjectPrxHelperBase implements controlePrx
{
    private static final String __bass_name = "bass";

    public byte[] bass(byte[] theSong, int level)
    {
        return bass(theSong, level, null, false);
    }

    public byte[] bass(byte[] theSong, int level, java.util.Map<String, String> __ctx)
    {
        return bass(theSong, level, __ctx, true);
    }

    private byte[] bass(byte[] theSong, int level, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "bass", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("bass");
                    __delBase = __getDelegate(false);
                    _controleDel __del = (_controleDel)__delBase;
                    return __del.bass(theSong, level, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_bass(byte[] theSong, int level)
    {
        return begin_bass(theSong, level, null, false, null);
    }

    public Ice.AsyncResult begin_bass(byte[] theSong, int level, java.util.Map<String, String> __ctx)
    {
        return begin_bass(theSong, level, __ctx, true, null);
    }

    public Ice.AsyncResult begin_bass(byte[] theSong, int level, Ice.Callback __cb)
    {
        return begin_bass(theSong, level, null, false, __cb);
    }

    public Ice.AsyncResult begin_bass(byte[] theSong, int level, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_bass(theSong, level, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_bass(byte[] theSong, int level, Callback_controle_bass __cb)
    {
        return begin_bass(theSong, level, null, false, __cb);
    }

    public Ice.AsyncResult begin_bass(byte[] theSong, int level, java.util.Map<String, String> __ctx, Callback_controle_bass __cb)
    {
        return begin_bass(theSong, level, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_bass(byte[] theSong, int level, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__bass_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __bass_name, __cb);
        try
        {
            __result.__prepare(__bass_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            songHelper.write(__os, theSong);
            __os.writeInt(level);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public byte[] end_bass(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __bass_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            byte[] __ret;
            __ret = songHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __filter_name = "filter";

    public byte[] filter(byte[] theSong)
    {
        return filter(theSong, null, false);
    }

    public byte[] filter(byte[] theSong, java.util.Map<String, String> __ctx)
    {
        return filter(theSong, __ctx, true);
    }

    private byte[] filter(byte[] theSong, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "filter", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("filter");
                    __delBase = __getDelegate(false);
                    _controleDel __del = (_controleDel)__delBase;
                    return __del.filter(theSong, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_filter(byte[] theSong)
    {
        return begin_filter(theSong, null, false, null);
    }

    public Ice.AsyncResult begin_filter(byte[] theSong, java.util.Map<String, String> __ctx)
    {
        return begin_filter(theSong, __ctx, true, null);
    }

    public Ice.AsyncResult begin_filter(byte[] theSong, Ice.Callback __cb)
    {
        return begin_filter(theSong, null, false, __cb);
    }

    public Ice.AsyncResult begin_filter(byte[] theSong, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_filter(theSong, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_filter(byte[] theSong, Callback_controle_filter __cb)
    {
        return begin_filter(theSong, null, false, __cb);
    }

    public Ice.AsyncResult begin_filter(byte[] theSong, java.util.Map<String, String> __ctx, Callback_controle_filter __cb)
    {
        return begin_filter(theSong, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_filter(byte[] theSong, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__filter_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __filter_name, __cb);
        try
        {
            __result.__prepare(__filter_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            songHelper.write(__os, theSong);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public byte[] end_filter(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __filter_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            byte[] __ret;
            __ret = songHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static controlePrx checkedCast(Ice.ObjectPrx __obj)
    {
        controlePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof controlePrx)
            {
                __d = (controlePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    controlePrxHelper __h = new controlePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static controlePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        controlePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof controlePrx)
            {
                __d = (controlePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    controlePrxHelper __h = new controlePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static controlePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        controlePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    controlePrxHelper __h = new controlePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static controlePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        controlePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    controlePrxHelper __h = new controlePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static controlePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        controlePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof controlePrx)
            {
                __d = (controlePrx)__obj;
            }
            else
            {
                controlePrxHelper __h = new controlePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static controlePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        controlePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            controlePrxHelper __h = new controlePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::Music::controle"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _controleDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _controleDelD();
    }

    public static void __write(IceInternal.BasicStream __os, controlePrx v)
    {
        __os.writeProxy(v);
    }

    public static controlePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            controlePrxHelper result = new controlePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
