// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface Central extends com.zeroc.Ice.Object
{
    music[] findByName(String nameSong, com.zeroc.Ice.Current current);

    music[] findByAuth(String nameAuthor, com.zeroc.Ice.Current current);

    music[] findByAlbum(String nameAlbum, com.zeroc.Ice.Current current);

    music[] findByGenre(String nameGenre, com.zeroc.Ice.Current current);

    String getStreamer(com.zeroc.Ice.Current current);

    music[] getAllAvailableSong(com.zeroc.Ice.Current current);

    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::appli::Central"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::appli::Central";
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_findByName(Central obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_nameSong;
        iceP_nameSong = istr.readString();
        inS.endReadParams();
        music[] ret = obj.findByName(iceP_nameSong, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        repositoryHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_findByAuth(Central obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_nameAuthor;
        iceP_nameAuthor = istr.readString();
        inS.endReadParams();
        music[] ret = obj.findByAuth(iceP_nameAuthor, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        repositoryHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_findByAlbum(Central obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_nameAlbum;
        iceP_nameAlbum = istr.readString();
        inS.endReadParams();
        music[] ret = obj.findByAlbum(iceP_nameAlbum, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        repositoryHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_findByGenre(Central obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_nameGenre;
        iceP_nameGenre = istr.readString();
        inS.endReadParams();
        music[] ret = obj.findByGenre(iceP_nameGenre, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        repositoryHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getStreamer(Central obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String ret = obj.getStreamer(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllAvailableSong(Central obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        music[] ret = obj.getAllAvailableSong(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        repositoryHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    final static String[] _iceOps =
    {
        "findByAlbum",
        "findByAuth",
        "findByGenre",
        "findByName",
        "getAllAvailableSong",
        "getStreamer",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_findByAlbum(this, in, current);
            }
            case 1:
            {
                return _iceD_findByAuth(this, in, current);
            }
            case 2:
            {
                return _iceD_findByGenre(this, in, current);
            }
            case 3:
            {
                return _iceD_findByName(this, in, current);
            }
            case 4:
            {
                return _iceD_getAllAvailableSong(this, in, current);
            }
            case 5:
            {
                return _iceD_getStreamer(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
