// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface CentralPrx extends com.zeroc.Ice.ObjectPrx
{
    default music[] findByName(String nameSong)
    {
        return findByName(nameSong, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default music[] findByName(String nameSong, java.util.Map<String, String> context)
    {
        return _iceI_findByNameAsync(nameSong, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<music[]> findByNameAsync(String nameSong)
    {
        return _iceI_findByNameAsync(nameSong, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<music[]> findByNameAsync(String nameSong, java.util.Map<String, String> context)
    {
        return _iceI_findByNameAsync(nameSong, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<music[]> _iceI_findByNameAsync(String iceP_nameSong, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<music[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByName", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nameSong);
                 }, istr -> {
                     music[] ret;
                     ret = repositoryHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default music[] findByAuth(String nameAuthor)
    {
        return findByAuth(nameAuthor, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default music[] findByAuth(String nameAuthor, java.util.Map<String, String> context)
    {
        return _iceI_findByAuthAsync(nameAuthor, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<music[]> findByAuthAsync(String nameAuthor)
    {
        return _iceI_findByAuthAsync(nameAuthor, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<music[]> findByAuthAsync(String nameAuthor, java.util.Map<String, String> context)
    {
        return _iceI_findByAuthAsync(nameAuthor, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<music[]> _iceI_findByAuthAsync(String iceP_nameAuthor, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<music[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByAuth", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nameAuthor);
                 }, istr -> {
                     music[] ret;
                     ret = repositoryHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default music[] findByAlbum(String nameAlbum)
    {
        return findByAlbum(nameAlbum, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default music[] findByAlbum(String nameAlbum, java.util.Map<String, String> context)
    {
        return _iceI_findByAlbumAsync(nameAlbum, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<music[]> findByAlbumAsync(String nameAlbum)
    {
        return _iceI_findByAlbumAsync(nameAlbum, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<music[]> findByAlbumAsync(String nameAlbum, java.util.Map<String, String> context)
    {
        return _iceI_findByAlbumAsync(nameAlbum, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<music[]> _iceI_findByAlbumAsync(String iceP_nameAlbum, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<music[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByAlbum", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nameAlbum);
                 }, istr -> {
                     music[] ret;
                     ret = repositoryHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default music[] findByGenre(String nameGenre)
    {
        return findByGenre(nameGenre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default music[] findByGenre(String nameGenre, java.util.Map<String, String> context)
    {
        return _iceI_findByGenreAsync(nameGenre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<music[]> findByGenreAsync(String nameGenre)
    {
        return _iceI_findByGenreAsync(nameGenre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<music[]> findByGenreAsync(String nameGenre, java.util.Map<String, String> context)
    {
        return _iceI_findByGenreAsync(nameGenre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<music[]> _iceI_findByGenreAsync(String iceP_nameGenre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<music[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByGenre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nameGenre);
                 }, istr -> {
                     music[] ret;
                     ret = repositoryHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String getStreamer()
    {
        return getStreamer(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getStreamer(java.util.Map<String, String> context)
    {
        return _iceI_getStreamerAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getStreamerAsync()
    {
        return _iceI_getStreamerAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getStreamerAsync(java.util.Map<String, String> context)
    {
        return _iceI_getStreamerAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getStreamerAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStreamer", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default music[] getAllAvailableSong()
    {
        return getAllAvailableSong(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default music[] getAllAvailableSong(java.util.Map<String, String> context)
    {
        return _iceI_getAllAvailableSongAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<music[]> getAllAvailableSongAsync()
    {
        return _iceI_getAllAvailableSongAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<music[]> getAllAvailableSongAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllAvailableSongAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<music[]> _iceI_getAllAvailableSongAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<music[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllAvailableSong", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     music[] ret;
                     ret = repositoryHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CentralPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), CentralPrx.class, _CentralPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CentralPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), CentralPrx.class, _CentralPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CentralPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), CentralPrx.class, _CentralPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CentralPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), CentralPrx.class, _CentralPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static CentralPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, CentralPrx.class, _CentralPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static CentralPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, CentralPrx.class, _CentralPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default CentralPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (CentralPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default CentralPrx ice_adapterId(String newAdapterId)
    {
        return (CentralPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default CentralPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (CentralPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default CentralPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (CentralPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default CentralPrx ice_invocationTimeout(int newTimeout)
    {
        return (CentralPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default CentralPrx ice_connectionCached(boolean newCache)
    {
        return (CentralPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default CentralPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (CentralPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CentralPrx ice_secure(boolean b)
    {
        return (CentralPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default CentralPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (CentralPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CentralPrx ice_preferSecure(boolean b)
    {
        return (CentralPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default CentralPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (CentralPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default CentralPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (CentralPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default CentralPrx ice_collocationOptimized(boolean b)
    {
        return (CentralPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default CentralPrx ice_twoway()
    {
        return (CentralPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default CentralPrx ice_oneway()
    {
        return (CentralPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default CentralPrx ice_batchOneway()
    {
        return (CentralPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default CentralPrx ice_datagram()
    {
        return (CentralPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default CentralPrx ice_batchDatagram()
    {
        return (CentralPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default CentralPrx ice_compress(boolean co)
    {
        return (CentralPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default CentralPrx ice_timeout(int t)
    {
        return (CentralPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default CentralPrx ice_connectionId(String connectionId)
    {
        return (CentralPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default CentralPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (CentralPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::appli::Central";
    }
}
