// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface Streamer extends Ice.Object,
                                  _StreamerOperations, _StreamerOperationsNC
{
    public static final String ice_staticId = "::appli::Streamer";

    public static final long serialVersionUID = 8995484578092546898L;
}
