// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface _CentralOperationsNC
{
    music[] findByName(String nameSong);

    music[] findByAuth(String nameAuthor);

    music[] findByAlbum(String nameAlbum);

    music[] findByGenre(String nameGenre);

    String getStreamer();

    music[] getAllAvailableSong();
}
