// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface _CentralOperations
{
    music[] findByName(String nameSong, Ice.Current __current);

    music[] findByAuth(String nameAuthor, Ice.Current __current);

    music[] findByAlbum(String nameAlbum, Ice.Current __current);

    music[] findByGenre(String nameGenre, Ice.Current __current);

    String getStreamer(Ice.Current __current);

    music[] getAllAvailableSong(Ice.Current __current);
}
