// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface _StreamerOperations
{
    music[] getRepertoire(Ice.Current __current);

    boolean addSong(byte[] theSong, String nameSong, Ice.Current __current);

    boolean checkStream(String nameSong, Ice.Current __current);
}
