// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

/**
 * Provides type-specific helper functions.
 **/
public final class StreamerPrxHelper extends Ice.ObjectPrxHelperBase implements StreamerPrx
{
    private static final String __addSong_name = "addSong";

    public void addSong(byte[] theSong, String nameSong, String author, String album, String genre)
    {
        addSong(theSong, nameSong, author, album, genre, null, false);
    }

    public void addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx)
    {
        addSong(theSong, nameSong, author, album, genre, __ctx, true);
    }

    private void addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_addSong(begin_addSong(theSong, nameSong, author, album, genre, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, null, false, false, null);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, Ice.Callback __cb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, Callback_Streamer_addSong __cb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx, Callback_Streamer_addSong __cb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_addSong(theSong, nameSong, author, album, genre, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_addSong(byte[] theSong, 
                                          String nameSong, 
                                          String author, 
                                          String album, 
                                          String genre, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_addSong(theSong, 
                             nameSong, 
                             author, 
                             album, 
                             genre, 
                             __ctx, 
                             __explicitCtx, 
                             __synchronous, 
                             new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_addSong(byte[] theSong, 
                                          String nameSong, 
                                          String author, 
                                          String album, 
                                          String genre, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__addSong_name, __cb);
        try
        {
            __result.prepare(__addSong_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            songHelper.write(__os, theSong);
            __os.writeString(nameSong);
            __os.writeString(author);
            __os.writeString(album);
            __os.writeString(genre);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_addSong(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __addSong_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static StreamerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), StreamerPrx.class, StreamerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static StreamerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), StreamerPrx.class, StreamerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static StreamerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), StreamerPrx.class, StreamerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static StreamerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), StreamerPrx.class, StreamerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static StreamerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, StreamerPrx.class, StreamerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static StreamerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, StreamerPrx.class, StreamerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::appli::Streamer"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, StreamerPrx v)
    {
        __os.writeProxy(v);
    }

    public static StreamerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            StreamerPrxHelper result = new StreamerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
