// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `app.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package appli;

public interface StreamerPrx extends Ice.ObjectPrx
{
    public void addSong(byte[] theSong, String nameSong, String author, String album, String genre);

    public void addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre);

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, Ice.Callback __cb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, Callback_Streamer_addSong __cb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, String nameSong, String author, String album, String genre, java.util.Map<String, String> __ctx, Callback_Streamer_addSong __cb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addSong(byte[] theSong, 
                                         String nameSong, 
                                         String author, 
                                         String album, 
                                         String genre, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_addSong(Ice.AsyncResult __result);
}
